export const COUNTRY_CODES = [
  { code: "+1", label: "+1 (US/CA)" },
  { code: "+44", label: "+44 (UK)" },
  { code: "+91", label: "+91 (India)" },
  { code: "+61", label: "+61 (Australia)" },
  { code: "+81", label: "+81 (Japan)" },
  { code: "+49", label: "+49 (Germany)" },
  { code: "+33", label: "+33 (France)" },
  { code: "+39", label: "+39 (Italy)" },
  { code: "+34", label: "+34 (Spain)" },
  { code: "+55", label: "+55 (Brazil)" },
  { code: "+86", label: "+86 (China)" },
  { code: "+82", label: "+82 (Korea)" },
  { code: "+65", label: "+65 (Singapore)" },
  { code: "+971", label: "+971 (UAE)" },
  { code: "+966", label: "+966 (Saudi Arabia)" },
  { code: "+27", label: "+27 (South Africa)" },
  { code: "+31", label: "+31 (Netherlands)" },
  { code: "+32", label: "+32 (Belgium)" },
  { code: "+41", label: "+41 (Switzerland)" },
  { code: "+46", label: "+46 (Sweden)" },
  { code: "+47", label: "+47 (Norway)" },
  { code: "+358", label: "+358 (Finland)" },
  { code: "+353", label: "+353 (Ireland)" },
  { code: "+52", label: "+52 (Mexico)" },
  { code: "+54", label: "+54 (Argentina)" },
  { code: "+57", label: "+57 (Colombia)" },
  { code: "+7", label: "+7 (Russia)" },
  { code: "+90", label: "+90 (Turkey)" },
  { code: "+92", label: "+92 (Pakistan)" },
  { code: "+880", label: "+880 (Bangladesh)" },
  { code: "+94", label: "+94 (Sri Lanka)" },
  { code: "+64", label: "+64 (New Zealand)" },
  { code: "+48", label: "+48 (Poland)" },
  { code: "+420", label: "+420 (Czech)" },
  { code: "+43", label: "+43 (Austria)" },
  { code: "+45", label: "+45 (Denmark)" },
  { code: "+30", label: "+30 (Greece)" },
  { code: "+351", label: "+351 (Portugal)" },
  { code: "+234", label: "+234 (Nigeria)" },
  { code: "+254", label: "+254 (Kenya)" },
  { code: "+20", label: "+20 (Egypt)" },
  { code: "+213", label: "+213 (Algeria)" },
  { code: "+212", label: "+212 (Morocco)" },
  { code: "+60", label: "+60 (Malaysia)" },
  { code: "+62", label: "+62 (Indonesia)" },
  { code: "+63", label: "+63 (Philippines)" },
  { code: "+66", label: "+66 (Thailand)" },
  { code: "+84", label: "+84 (Vietnam)" },
  { code: "+98", label: "+98 (Iran)" },
  { code: "+972", label: "+972 (Israel)" },
] as const;

export const PHONE_REGEX = /^\d{10}$/;
